name: Publish
on: 
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . -t lgohr/asdf:${{ github.sha }} -t lgohr/asdf:latest
    - name: Login to Registry
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Push to Registry
      run: |
        docker push lgohr/asdf:${{ github.sha }}
        docker push lgohr/asdf:latest
    - name: Logout
      run: docker logout
      
